# config
cover: //blog.ghost.org/content/images/2013/Nov/cover.png
logo: //blog.ghost.org/content/images/2013/Nov/bloglogo_1-1.png
bio: 'Relax , thinking and coding.'

# Content
excerpt_link: Read More

# Miscellaneous
rss:
